import { registerEnumType } from '@nestjs/graphql';

export enum OriginalLanguageType {
    JA = "JA",
    KO = "KO",
    ZH = "ZH",
    ZH_HK = "ZH_HK",
    EN = "EN",
    AR = "AR",
    AZ = "AZ",
    BN = "BN",
    BG = "BG",
    MY = "MY",
    CA = "CA",
    HR = "HR",
    CS = "CS",
    DA = "DA",
    NL = "NL",
    EO = "EO",
    ET = "ET",
    TL = "TL",
    FI = "FI",
    FR = "FR",
    DE = "DE",
    EL = "EL",
    HE = "HE",
    HI = "HI",
    HU = "HU",
    ID = "ID",
    IT = "IT",
    KK = "KK",
    LA = "LA",
    LT = "LT",
    MS = "MS",
    MN = "MN",
    NE = "NE",
    NO = "NO",
    FA = "FA",
    PL = "PL",
    PT = "PT",
    PT_BR = "PT_BR",
    RO = "RO",
    RU = "RU",
    SR = "SR",
    SK = "SK",
    ES = "ES",
    ES_LA = "ES_LA",
    SV = "SV",
    TA = "TA",
    TH = "TH",
    TR = "TR",
    UK = "UK",
    VI = "VI"
}


registerEnumType(OriginalLanguageType, { name: 'OriginalLanguageType', description: undefined })
